# Generated by Django 4.1 on 2022-08-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='customer',
            new_name='product_owner',
        ),
    ]
