# Generated by Django 4.1 on 2022-08-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_customer_products_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='mountain.jpg', upload_to='products-pics'),
        ),
    ]
