# Generated by Django 4.1 on 2022-08-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_order_rename_title_products_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='mountain.jpg', null=True, upload_to='products-pics'),
        ),
    ]
