# Generated by Django 4.1 on 2022-09-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_products_category_products_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_category',
            new_name='category',
        ),
    ]
