from django.utils.translation import gettext_lazy as _

COUNTRIES_CHOICES = [
    ('AF', _('Afghanistan')), ('AX', _('Åland Islands')), ('AL', _('Albania')),
    ('DZ', _('Algeria')), ('AS', _('American Samoa')), ('AD', _('Andorra')),
    ('AO', _('Angola')), ('AI', _('Anguilla')), ('AQ', _('Antarctica')),
    ('AG', _('Antigua and Barbuda')), ('AR', _('Argentina')), ('AM', _('Armenia')),
    ('AW', _('Aruba')), ('AU', _('Australia')), ('AT', _('Austria')),
    ('AZ', _('Azerbaijan')), ('BS', _('Bahamas')), ('BH', _('Bahrain')),
    ('BD', _('Bangladesh')), ('BB', _('Barbados')), ('BY', _('Belarus')),
    ('BE', _('Belgium')), ('BZ', _('Belize')), ('BJ', _('Benin')),
    ('BM', _('Bermuda')), ('BT', _('Bhutan')), ('BO', _('Bolivia')),
    ('BQ', _('Bonaire, Sint Eustatius and Saba')), ('BA', _('Bosnia and Herzegovina')),
    ('BW', _('Botswana')), ('BV', _('Bouvet Island')), ('BR', _('Brazil')),
    ('IO', _('British Indian Ocean Territory')), ('BN', _('Brunei Darussalam')),
    ('BG', _('Bulgaria')), ('BF', _('Burkina Faso')), ('BI', _('Burundi')),
    ('CV', _('Cabo Verde')), ('KH', _('Cambodia')), ('CM', _('Cameroon')),
    ('CA', _('Canada')), ('KY', _('Cayman Islands')),
    ('CF', _('Central African Republic')), ('TD', _('Chad')), ('CL', _('Chile')),
    ('CN', _('China')), ('CO', _('Colombia')), ('KM', _('Comoros')),
    ('CD', _('Congo')), ('CK', _('Cook Islands')), ('CR', _('Costa Rica')),
    ('HR', _('Croatia')), ('CU', _('Cuba')), ('CW', _('Curaçao')), ('CY', _('Cyprus')),
    ('CZ', _('Czechia')), ('DK', _('Denmark')), ('DJ', _('Djibouti')),
    ('DM', _('Dominica')), ('DO', _('Dominican Republic')), ('EC', _('Ecuador')),
    ('EG', _('Egypt')), ('SV', _('El Salvador')), ('GQ', _('Equatorial Guinea')),
    ('ER', _('Eritrea')), ('EE', _('Estonia')), ('SZ', _('Eswatini')),
    ('ET', _('Ethiopia')), ('FK', _('Falkland Islands  [Malvinas]')),
    ('FO', _('Faroe Islands')), ('FJ', _('Fiji')), ('FI', _('Finland')),
    ('FR', _('France')), ('GF', _('French Guiana')), ('PF', _('French Polynesia')),
    ('TF', _('French Southern Territories')), ('GA', _('Gabon')), ('GM', _('Gambia')),
    ('GE', _('Georgia')), ('DE', _('Germany')), ('GH', _('Ghana')),
    ('GI', _('Gibraltar')), ('GR', _('Greece')), ('GL', _('Greenland')),
    ('GD', _('Grenada')), ('GP', _('Guadeloupe')), ('GU', _('Guam')),
    ('GT', _('Guatemala')), ('GG', _('Guernsey')), ('GN', _('Guinea')),
    ('GW', _('Guinea-Bissau')), ('GY', _('Guyana')), ('HT', _('Haiti')),
    ('HM', _('Heard Island and McDonald Islands')), ('VA', _('Holy See')),
    ('HN', _('Honduras')), ('HK', _('Hong Kong')), ('HU', _('Hungary')),
    ('IS', _('Iceland')), ('IN', _('India')), ('ID', _('Indonesia')),
    ('IR', _('Iran')), ('IQ', _('Iraq')), ('IE', _('Ireland')),
    ('IM', _('Isle of Man')), ('IL', _('Israel')), ('IT', _('Italy')),
    ('CI', _('Ivory Coast')), ('JM', _('Jamaica')), ('JP', _('Japan')),
    ('JE', _('Jersey')), ('JO', _('Jordan')), ('KZ', _('Kazakhstan')),
    ('KE', _('Kenya')), ('KI', _('Kiribati')),
    ('KP', _('Korea (Democratic Republic of)')), ('KR', _('Korea (Republic of)')),
    ('KW', _('Kuwait')), ('KG', _('Kyrgyzstan')), ('LA', _('Lao Democratic Republic')),
    ('LV', _('Latvia')), ('LB', _('Lebanon')), ('LS', _('Lesotho')),
    ('LR', _('Liberia')), ('LY', _('Libya')), ('LI', _('Liechtenstein')),
    ('LT', _('Lithuania')), ('LU', _('Luxembourg')), ('MO', _('Macao')),
    ('MG', _('Madagascar')), ('MW', _('Malawi')), ('MY', _('Malaysia')),
    ('MV', _('Maldives')), ('ML', _('Mali')), ('MT', _('Malta')),
    ('MH', _('Marshall Islands')), ('MQ', _('Martinique')), ('MR', _('Mauritania')),
    ('MU', _('Mauritius')), ('YT', _('Mayotte')), ('MX', _('Mexico')),
    ('FM', _('Micronesia (Federated States of)')), ('MD', _('Moldova (the Republic of)')),
    ('MC', _('Monaco')), ('MN', _('Mongolia')), ('ME', _('Montenegro')),
    ('MS', _('Montserrat')), ('MA', _('Morocco')), ('MZ', _('Mozambique')),
    ('MM', _('Myanmar')), ('NA', _('Namibia')), ('NR', _('Nauru')),
    ('NP', _('Nepal')), ('NL', _('Netherlands')), ('NC', _('New Caledonia')),
    ('NZ', _('New Zealand')), ('NI', _('Nicaragua')), ('NE', _('Niger')),
    ('NG', _('Nigeria')), ('NU', _('Niue')), ('NF', _('Norfolk Island')),
    ('MK', _('North Macedonia')), ('MP', _('Northern Mariana Islands')),
    ('NO', _('Norway')), ('OM', _('Oman')), ('PK', _('Pakistan')),
    ('PW', _('Palau')), ('PS', _('Palestine, State of')), ('PA', _('Panama')),
    ('PG', _('Papua New Guinea')), ('PY', _('Paraguay')), ('PE', _('Peru')),
    ('PH', _('Philippines')), ('PN', _('Pitcairn')), ('PL', _('Poland')),
    ('PT', _('Portugal')), ('PR', _('Puerto Rico')), ('QA', _('Qatar')),
    ('RE', _('Réunion')), ('RO', _('Romania')), ('RU', _('Russian Federation')),
    ('RW', _('Rwanda')), ('BL', _('Saint Barthélemy')),
    ('SH', _('Saint Helena, Ascension and Tristan da Cunha')),
    ('KN', _('Saint Kitts and Nevis')), ('LC', _('Saint Lucia')),
    ('MF', _('Saint Martin (French part)')), ('PM', _('Saint Pierre and Miquelon')),
    ('VC', _('Saint Vincent and the Grenadines')), ('WS', _('Samoa')),
    ('SM', _('San Marino')), ('ST', _('Sao Tome and Principe')),
    ('SA', _('Saudi Arabia')), ('SN', _('Senegal')), ('RS', _('Serbia')),
    ('SC', _('Seychelles')), ('SL', _('Sierra Leone')), ('SG', _('Singapore')),
    ('SX', _('Sint Maarten (Dutch part)')), ('SK', _('Slovakia')), ('SI', _('Slovenia')),
    ('SB', _('Solomon Islands')), ('SO', _('Somalia')), ('ZA', _('South Africa')),
    ('GS', _('South Georgia and the South Sandwich Islands')), ('SS', _('South Sudan')),
    ('ES', _('Spain')), ('LK', _('Sri Lanka')), ('SD', _('Sudan')), ('SR', _('Suriname')),
    ('SJ', _('Svalbard and Jan Mayen')), ('SE', _('Sweden')), ('CH', _('Switzerland')),
    ('SY', _('Syrian Arab Republic')), ('TW', _('Taiwan (Province of China)')),
    ('TJ', _('Tajikistan')), ('TZ', _('Tanzania, the United Republic of')),
    ('TH', _('Thailand')), ('TL', _('Timor-Leste')), ('TG', _('Togo')),
    ('TK', _('Tokelau')), ('TO', _('Tonga')), ('TT', _('Trinidad and Tobago')),
    ('TN', _('Tunisia')), ('TR', _('Turkey')), ('TM', _('Turkmenistan')),
    ('TC', _('Turks and Caicos Islands')), ('TV', _('Tuvalu')), ('UG', _('Uganda')),
    ('UA', _('Ukraine')), ('AE', _('United Arab Emirates')),
    ('GB', _('United Kingdom of Great Britain and Northern Ireland')),
    ('US', _('United States of America')), ('UY', _('Uruguay')), ('UZ', _('Uzbekistan')),
    ('VU', _('Vanuatu')), ('VE', _('Venezuela (Bolivarian Republic of)')),
    ('VN', _('Viet Nam')), ('VG', _('Virgin Islands (British)')),
    ('VI', _('Virgin Islands (U.S.)')), ('WF', _('Wallis and Futuna')),
    ('EH', _('Western Sahara')), ('YE', _('Yemen')),
    ('ZM', _('Zambia')), ('ZW', _('Zimbabwe')),
]

LANGUAGES = [
    ('aa', 'Afar'),
    ('ab', 'Abkhazian'),
    ('af', 'Afrikaans'),
    ('ak', 'Akan'),
    ('sq', 'Albanian'),
    ('am', 'Amharic'),
    ('ar', 'Arabic'),
    ('an', 'Aragonese'),
    ('hy', 'Armenian'),
    ('as', 'Assamese'),
    ('av', 'Avaric'),
    ('ae', 'Avestan'),
    ('ay', 'Aymara'),
    ('az', 'Azerbaijani'),
    ('ba', 'Bashkir'),
    ('bm', 'Bambara'),
    ('eu', 'Basque'),
    ('be', 'Belarusian'),
    ('bn', 'Bengali'),
    ('bh', 'Bihari languages'),
    ('bi', 'Bislama'),
    ('bo', 'Tibetan'),
    ('bs', 'Bosnian'),
    ('br', 'Breton'),
    ('bg', 'Bulgarian'),
    ('my', 'Burmese'),
    ('ca', 'Catalan; Valencian'),
    ('cs', 'Czech'),
    ('ch', 'Chamorro'),
    ('ce', 'Chechen'),
    ('zh', 'Chinese'),
    ('cu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
    ('cv', 'Chuvash'),
    ('kw', 'Cornish'),
    ('co', 'Corsican'),
    ('cr', 'Cree'),
    ('cy', 'Welsh'),
    ('cs', 'Czech'),
    ('da', 'Danish'),
    ('de', 'German'),
    ('dv', 'Divehi; Dhivehi; Maldivian'),
    ('nl', 'Dutch; Flemish'),
    ('dz', 'Dzongkha'),
    ('el', 'Greek, Modern (1453-)'),
    ('en', 'English'),
    ('eo', 'Esperanto'),
    ('et', 'Estonian'),
    ('eu', 'Basque'),
    ('ee', 'Ewe'),
    ('fo', 'Faroese'),
    ('fa', 'Persian'),
    ('fj', 'Fijian'),
    ('fi', 'Finnish'),
    ('fr', 'French'),
    ('fy', 'Western Frisian'),
    ('ff', 'Fulah'),
    ('Ga', 'Georgian'),
    ('de', 'German'),
    ('gd', 'Gaelic; Scottish Gaelic'),
    ('ga', 'Irish'),
    ('gl', 'Galician'),
    ('gv', 'Manx'),
    ('el', 'Greek, Modern (1453-)'),
    ('gn', 'Guarani'),
    ('gu', 'Gujarati'),
    ('ht', 'Haitian; Haitian Creole'),
    ('ha', 'Hausa'),
    ('he', 'Hebrew'),
    ('hz', 'Herero'),
    ('hi', 'Hindi'),
    ('ho', 'Hiri Motu'),
    ('hr', 'Croatian'),
    ('hu', 'Hungarian'),
    ('hy', 'Armenian'),
    ('ig', 'Igbo'),
    ('is', 'Icelandic'),
    ('io', 'Ido'),
    ('ii', 'Sichuan Yi; Nuosu'),
    ('iu', 'Inuktitut'),
    ('ie', 'Interlingue; Occidental'),
    ('ia', 'Interlingua (International Auxiliary Language Association)'),
    ('id', 'Indonesian'),
    ('ik', 'Inupiaq'),
    ('is', 'Icelandic'),
    ('it', 'Italian'),
    ('jv', 'Javanese'),
    ('ja', 'Japanese'),
    ('kl', 'Kalaallisut; Greenlandic'),
    ('kn', 'Kannada'),
    ('ks', 'Kashmiri'),
    ('ka', 'Georgian'),
    ('kr', 'Kanuri'),
    ('kk', 'Kazakh'),
    ('km', 'Central Khmer'),
    ('ki', 'Kikuyu; Gikuyu'),
    ('rw', 'Kinyarwanda'),
    ('ky', 'Kirghiz; Kyrgyz'),
    ('kv', 'Komi'),
    ('kg', 'Kongo'),
    ('ko', 'Korean'),
    ('kj', 'Kuanyama; Kwanyama'),
    ('ku', 'Kurdish'),
    ('lo', 'Lao'),
    ('la', 'Latin'),
    ('lv', 'Latvian'),
    ('li', 'Limburgan; Limburger; Limburgish'),
    ('ln', 'Lingala'),
    ('lt', 'Lithuanian'),
    ('lb', 'Luxembourgish; Letzeburgesch'),
    ('lu', 'Luba-Katanga'),
    ('lg', 'Ganda'),
    ('mk', 'Macedonian'),
    ('mh', 'Marshallese'),
    ('ml', 'Malayalam'),
    ('mi', 'Maori'),
    ('mr', 'Marathi'),
    ('ms', 'Malay'),
    ('Mi', 'Micmac'),
    ('mk', 'Macedonian'),
    ('mg', 'Malagasy'),
    ('mt', 'Maltese'),
    ('mn', 'Mongolian'),
    ('mi', 'Maori'),
    ('ms', 'Malay'),
    ('my', 'Burmese'),
    ('na', 'Nauru'),
    ('nv', 'Navajo; Navaho'),
    ('nr', 'Ndebele, South; South Ndebele'),
    ('nd', 'Ndebele, North; North Ndebele'),
    ('ng', 'Ndonga'),
    ('ne', 'Nepali'),
    ('nl', 'Dutch; Flemish'),
    ('nn', 'Norwegian Nynorsk; Nynorsk, Norwegian'),
    ('nb', 'Bokmål, Norwegian; Norwegian Bokmål'),
    ('no', 'Norwegian'),
    ('oc', 'Occitan (post 1500)'),
    ('oj', 'Ojibwa'),
    ('or', 'Oriya'),
    ('om', 'Oromo'),
    ('os', 'Ossetian; Ossetic'),
    ('pa', 'Panjabi; Punjabi'),
    ('fa', 'Persian'),
    ('pi', 'Pali'),
    ('pl', 'Polish'),
    ('pt', 'Portuguese'),
    ('ps', 'Pushto; Pashto'),
    ('qu', 'Quechua'),
    ('rm', 'Romansh'),
    ('ro', 'Romanian; Moldavian; Moldovan'),
    ('ro', 'Romanian; Moldavian; Moldovan'),
    ('rn', 'Rundi'),
    ('ru', 'Russian'),
    ('sg', 'Sango'),
    ('sa', 'Sanskrit'),
    ('si', 'Sinhala; Sinhalese'),
    ('sk', 'Slovak'),
    ('sk', 'Slovak'),
    ('sl', 'Slovenian'),
    ('se', 'Northern Sami'),
    ('sm', 'Samoan'),
    ('sn', 'Shona'),
    ('sd', 'Sindhi'),
    ('so', 'Somali'),
    ('st', 'Sotho, Southern'),
    ('es', 'Spanish; Castilian'),
    ('sq', 'Albanian'),
    ('sc', 'Sardinian'),
    ('sr', 'Serbian'),
    ('ss', 'Swati'),
    ('su', 'Sundanese'),
    ('sw', 'Swahili'),
    ('sv', 'Swedish'),
    ('ty', 'Tahitian'),
    ('ta', 'Tamil'),
    ('tt', 'Tatar'),
    ('te', 'Telugu'),
    ('tg', 'Tajik'),
    ('tl', 'Tagalog'),
    ('th', 'Thai'),
    ('bo', 'Tibetan'),
    ('ti', 'Tigrinya'),
    ('to', 'Tonga (Tonga Islands)'),
    ('tn', 'Tswana'),
    ('ts', 'Tsonga'),
    ('tk', 'Turkmen'),
    ('tr', 'Turkish'),
    ('tw', 'Twi'),
    ('ug', 'Uighur; Uyghur'),
    ('uk', 'Ukrainian'),
    ('ur', 'Urdu'),
    ('uz', 'Uzbek'),
    ('ve', 'Venda'),
    ('vi', 'Vietnamese'),
    ('vo', 'Volapük'),
    ('cy', 'Welsh'),
    ('wa', 'Walloon'),
    ('wo', 'Wolof'),
    ('xh', 'Xhosa'),
    ('yi', 'Yiddish'),
    ('yo', 'Yoruba'),
    ('za', 'Zhuang; Chuang'),
    ('zh', 'Chinese'),
    ('zu', 'Zulu')
]
