# Generated by Django 4.1.1 on 2022-09-08 09:55

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_recipe_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="external_video",
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
