# Generated by Django 4.1 on 2022-09-09 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0004_recipe_external_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='mountain.jpg', null=True, upload_to='category_images')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Appetizer', 'Appetizer'), ('Salad', 'Salad'), ('Main-Course', 'Main-Course'), ('Side-Dish', 'Side-Dish'), ('Baked-goods', 'Baked-goods'), ('Dessert', 'Dessert'), ('Pizza', 'Pizza'), ('Snack', 'Snack'), ('Vegeterian', 'Vegeterian'), ('Vegan', 'Vegan'), ('Middeterean', 'Middeterean'), ('Indian', 'Indian'), ('Asian', 'Asian'), ('BBQ', 'BBQ'), ('Middle Eastern', 'Middle Eastern'), ('Italian', 'Italian'), ('Other', 'Other')], default='Other', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='recipe_page', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='external_video',
            field=embed_video.fields.EmbedVideoField(help_text='Your recipe video', verbose_name='My online video'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('commenter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipe.recipe')),
            ],
        ),
    ]
