# Generated by Django 4.1 on 2022-09-09 13:41

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_category_recipe_category_recipe_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='external_video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Your recipe video', verbose_name='My online video'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
