# Generated by Django 4.1 on 2022-09-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0007_alter_recipe_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Breakfast", "Breakfast"),
                    ("Dinner", "Dinner"),
                    ("Side Dish", "Side Dish"),
                    ("Vegeterian", "Vegeterian"),
                    ("Pizza", "Pizza"),
                    ("Pasta", "Pasta"),
                ],
                default="Other",
                max_length=30,
                null=True,
            ),
        ),
    ]
